/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppGrid: typeof import('./src/components/AppGrid.vue')['default']
    Dock: typeof import('./src/components/Dock.vue')['default']
    FrontendFrame: typeof import('./src/components/FrontendFrame.vue')['default']
    HomeScreen: typeof import('./src/components/HomeScreen.vue')['default']
    PhoneFrame: typeof import('./src/components/PhoneFrame.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}
