import type { PhoneAppDefinition } from '@/types';

export const BUILTIN_APPS: PhoneAppDefinition[] = [
  {
    id: 'summary',
    name: '总结',
    icon: 'fa-solid fa-list-check',
    defaultRoute: '',
    defaultVisible: true,
    defaultDock: false,
    defaultOrder: 0,
    load: () => import('@/apps/summary/index'),
  },
  {
    id: 'diary',
    name: '日记',
    icon: 'fa-solid fa-book',
    defaultRoute: '',
    defaultVisible: true,
    defaultDock: true,
    defaultOrder: 1,
    load: () => import('@/apps/diary/index'),
  },
  {
    id: 'extras',
    name: '番外',
    icon: 'fa-solid fa-feather',
    defaultRoute: '',
    defaultVisible: true,
    defaultDock: false,
    defaultOrder: 2,
    load: () => import('@/apps/extras/index'),
  },
  {
    id: 'forum',
    name: '论坛',
    icon: 'fa-solid fa-comments',
    defaultRoute: '',
    defaultVisible: true,
    defaultDock: false,
    defaultOrder: 3,
    load: () => import('@/apps/forum/index'),
  },
  {
    id: 'theater',
    name: '小剧场',
    icon: 'fa-solid fa-masks-theater',
    defaultRoute: '',
    defaultVisible: true,
    defaultDock: true,
    defaultOrder: 4,
    load: () => import('@/apps/theater/index'),
  },
  {
    id: 'letters',
    name: '书信',
    icon: 'fa-solid fa-envelope',
    defaultRoute: '',
    defaultVisible: true,
    defaultDock: false,
    defaultOrder: 5,
    load: () => import('@/apps/letters/index'),
  },
  {
    id: 'favorites',
    name: '收藏',
    icon: 'fa-solid fa-star',
    defaultRoute: '',
    defaultVisible: true,
    defaultDock: true,
    defaultOrder: 6,
    load: () => import('@/apps/favorites/index'),
  },
  {
    id: 'prompts',
    name: '提示词工坊',
    icon: 'fa-solid fa-wrench',
    defaultRoute: '',
    defaultVisible: true,
    defaultDock: false,
    defaultOrder: 7,
    load: () => import('@/apps/prompts/index'),
  },
  {
    id: 'chat-stats',
    name: '聊天统计',
    icon: 'fa-solid fa-chart-bar',
    defaultRoute: '',
    defaultVisible: true,
    defaultDock: false,
    defaultOrder: 8,
    load: () => import('@/apps/chat-stats/index'),
  },
  {
    id: 'chat-reader',
    name: '阅读聊天',
    icon: 'fa-solid fa-book-open',
    defaultRoute: '',
    defaultVisible: true,
    defaultDock: false,
    defaultOrder: 9,
    load: () => import('@/apps/chat-reader/index'),
  },
  {
    id: 'bagu',
    name: '八股去除',
    icon: 'fa-solid fa-broom',
    defaultRoute: '',
    defaultVisible: true,
    defaultDock: false,
    defaultOrder: 10,
    load: () => import('@/apps/bagu/index'),
  },
  {
    id: 'settings',
    name: '设置',
    icon: 'fa-solid fa-gear',
    defaultRoute: '',
    defaultVisible: true,
    defaultDock: true,
    defaultOrder: 11,
    load: () => import('@/apps/settings/index'),
  },
];
